### ISSUE TITLE
readHostPortM fails if the hostname contains an underscore

### ISSUE THREAD

**Issue by neilco** [mongodb-haskell/mongodb#108]
It's come to my attention that `readHostPortM` fails if the hostname is snake-cased, Specifically, it produces the following error:

```shell
unexpected '_'
expecting letter, digit, "-", ".", white space, end of input or ":"
```

This can be tracked down to [this line](https://github.com/mongodb-haskell/mongodb/blob/60c10bb5cce70daaddbd7fc92ea34b1339306510/Database/MongoDB/Connection.hs#L89) in **Connect.hs**. The fix is to extend it thusly:

```haskell
hostname = many1 (letter <|> digit <|> char '-' <|> char '.' <|> char '_')
```

That's two hours of my life I'm not getting back 😞

**Comment by VictorDenisov** [comment]
Thanks for the bug report! Sorry for two hours of your life.
