### ISSUE TITLE
Release for GHC 8.8 support

### ISSUE THREAD

**Issue by maksbotan** [mongodb-haskell/mongodb#110]
Hey @VictorDenisov!

Thanks for updating `bson` to support GHC-8.8. Can you please now relax constraint on `bson` in this package? Now it has `bson < 0.4`, which prevents it to pick you `bson-0.4.0.0` and subsequently blocks the build on GHC-8.8. New hackage release will be needed too.

Thanks!

**Comment by VictorDenisov** [comment]
Released
