### ISSUE TITLE
Replace depriciated opCodes with OP_MSG and update associated wire protocol.

### ISSUE THREAD

**Issue by antarestrader** [mongodb-haskell/mongodb#123]
https://github.com/mongodb-haskell/mongodb/blob/3bb466c8180f28f8528fc4b1e3f59773c48d821e/Database/MongoDB/Internal/Protocol.hs#L410

https://github.com/mongodb-haskell/mongodb/blob/3bb466c8180f28f8528fc4b1e3f59773c48d821e/Database/MongoDB/Internal/Protocol.hs#L330

opCode values other than `OP_MSG` (2013) are [depreciated starting with Version 5](https://docs.mongodb.com/v5.0/reference/mongodb-wire-protocol/#std-label-wp-request-opcodes).  Since version 3.6 `OP_MSG` has been the preferred request method.   

`putNotice` and `putRequest` also need to be updtaed to match the [OP_MSG wire protocol](https://docs.mongodb.com/v5.0/reference/mongodb-wire-protocol/#std-label-wire-op-msg).

Doing so may partially or fully address issues #94, #97, #107, #112

**Comment by kfiz** [comment]
@VictorDenisov I think this can be closed, as https://github.com/mongodb-haskell/mongodb/pull/137 was merged. Would you agree?

**Comment by VictorDenisov** [comment]
Yep. Totally!
