### ISSUE TITLE
Documentation on best practices with Pipe

### ISSUE THREAD

**Issue by why-not-try-calmer** [mongodb-haskell/mongodb#125]
As far as I can see that Hackage documentation of this packages makes no mention of how to take advantage of the `Pipe` type; for example it does not help the new user determine if/when they should reuse a `Pipe` between several requests. This can make a very big difference to application architecture design, i.e. should I keep an IORef or MVar around with a ready Pipe? What strategy should I use to deprecate / regenerate my Pipe?

I would be happy to make a PR with this information but first I'd like to hear what the maintainer(s) recommend as far as reusing `Pipe` is concerned.

**Comment by VictorDenisov** [comment]
Which Pipe are you referring to? I thought this one was well documented that it's a thread safe: https://github.com/mongodb-haskell/mongodb/blob/master/Database/MongoDB/Internal/Protocol.hs#L198

**Comment by why-not-try-calmer** [comment]
> Which Pipe are you referring to? I thought this one was well documented that it's a thread safe: https://github.com/mongodb-haskell/mongodb/blob/master/Database/MongoDB/Internal/Protocol.hs#L198

I am referring to the `Pipe` type introduced on https://hackage.haskell.org/package/mongoDB-2.7.1.1/docs/Database-MongoDB-Connection.html. This page does not allow the user to answer the following questions:
- Can I reuse a Pipe value?
- If yes, for how long?

A typical case where these questions are important is when the user is writing a server application connected via `Database.MongoDB.Transport.Tls.connect` (which is required, if I am not mistaken, if your database host is MongoDb Atlas). In that case you'll want to authenticate as few times as possible, which is when the app starts and as many times as you run into a `ConnectionFailure`. By contrast if you don't reuse `Pipe` you'll neehave to authenticate every single query, which is less than ideal.

**Comment by why-not-try-calmer** [comment]
Also while we're at it @VictorDenisov most recent MongoDB providers offer users to connect using "connection strings" of the form `mongodb://username:password@host:port/[database]?ssl=true` ? That's typically what database APIs expect from clients.

**Comment by VictorDenisov** [comment]
One could probably add more documentation stating that it's safe to reuse this connection between many clients and multiple times. The docs tried to express it in one phrase - thread safe. So it is safe to use it multiple times and concurrently.

I'm not sure I understand the latter question. Are you asking why this driver doesn't support "connection strings" of this format?

**Comment by why-not-try-calmer** [comment]
> One could probably add more documentation stating that it's safe to reuse this connection between many clients and multiple times. The docs tried to express it in one phrase - thread safe. So it is safe to use it multiple times and concurrently.
> 
> I'm not sure I understand the latter question. Are you asking why this driver doesn't support "connection strings" of this format?

Thank you Victor for your reply.

Regarding the reusability question, yes, it would be very serviceable for the user to know that they may -- and are encouraged -- to reuse `Pipe`s for the indefinite amount of time that their application might be running. It's not just a matter of thread safety, it's a matter of whether -- and when -- users should expect Pipes to close, so that they can prepare for it when designing their application. Recently I've toyed around with this library and I've found out that my `Pipe`s (handling a connection to a MongoAtlas ReplicaSet) closed every now and then, so that I need to catch them closing and recreate them accordingly.

Regarding connection strings, my question is whether they are supported and, if yes, how to use them. My remark above was just that it's a very popular way of referencing connection settings, and indeed all Mongo drivers in other languages have, so I probably missed it.

**Comment by why-not-try-calmer** [comment]
Any news @VictorDenisov ? I'd be glad to try and help with either the docs or the connection string / URI, but I'd like to know where you stand on these questions :)

**Comment by VictorDenisov** [comment]
Sorry, I didn't realize you were expecting input from me. Do I understand correctly that you asking whether connection strings should be implemented/documented in the library?

**Comment by VictorDenisov** [comment]
I have to admit I haven't touched Pipes in a while, and I'm not aware when they may close and for what reasons. I would expect them to be open all the time. If they get closed from time to time for some reasons we need to look into why they close on case by case basis.

Regarding connection strings. Parsing a connection string would be a natural thing to do in a language like javascript which is used for mongodb command line tool. In haskell it's more conventional to build internal DSL languages for this type of structures. For example:
def { host = "host", port = "port" }
would create a connection structure with custom host and port and other fields set to default values.

This way the parsing is done by the compiler itself instead of building additional structures for parsing connection strings.
If you are thinking about improving the interface for connecting to the database I would suggest to think along those lines.

**Comment by why-not-try-calmer** [comment]
Thanks for your answer.

Okay, I see what how one could perhaps convey what you said about Pipes to the user. I'll make a PR.

Regarding connection strings: yeah thanks, I know how to parse things, the thing is that I hadn't looked at the code of this library and I thought these URI strings represented parameters alien to this library, which I now realize, is not the case :) I'll do some research and hopefully  make a PR about this too.
