### ISSUE TITLE
Support mongodb 6.0 ?

### ISSUE THREAD

**Issue by kfiz** [mongodb-haskell/mongodb#135]
mongodb removed some opcodes in 6.0. that `mongodb-haskell` is using. See:
https://dochub.mongodb.org/core/legacy-opcode-removal

Are there plans on updating this driver so it supports 6.0?

**Comment by VictorDenisov** [comment]
Contributions are welcome :)

**Comment by kfiz** [comment]
Ok. ;) 
I can see there is a test suite. So is it save to assume that once all of these pass on a local machine with mongoDB 6.0 running at localhost then we should be ok?
