### ISSUE TITLE
Aggregate support for MongoDB >= 2.6

### ISSUE THREAD

**Issue by spl** [mongodb-haskell/mongodb#16]
In MongoDB 2.6, `aggregate` was [changed to return a cursor](http://docs.mongodb.org/manual/release-notes/2.6/#rn-2-6-aggregation-cursor) instead of an array of all results. I created a test (#15) to see if the current implementation of `aggregate` worked for 2.6, and I was surprised to discover that it did. Is this to be expected? Should a new version of `aggregate` be created for working with a cursor?

**Comment by gregwebs** [comment]
Are you running 2.6 then? What is Travis running?

**Comment by spl** [comment]
> Are you running 2.6 then?

We're working on switching to it. I tried 2.6 locally on my Mac via Homebrew.

> What is Travis running?

Good question. I don't know, and I don't see it [here](http://docs.travis-ci.com/user/database-setup/#MongoDB).

**Comment by gregwebs** [comment]
looks like [2.4](https://github.com/travis-ci/travis-ci/issues/2246). That is good: it will make sure we maintain backwards compatibility.

**Comment by VictorDenisov** [comment]
@spl, what was changed is the command line interface for mongo db. The haskell driver uses the mongodb wired protocol for communication with the server. The protocol hasn't changed. I assume we can close this issue. If I misunderstood something please reopen it.

**Comment by spl** [comment]
@VictorDenisov Apologies for the delayed response. I agree. It wasn't an issue.
