### ISSUE TITLE
Release to Hackage a GHC-7.10 compatible version

### ISSUE THREAD

**Issue by Daniel-Diaz** [mongodb-haskell/mongodb#19]
It is nice that mongoDB is compatible with GHC-7.10 since https://github.com/mongodb-haskell/mongodb/commit/d548af688ebb177a0fb659ec333a2e32d39b7b25. Is it possible to enjoy this in the version in Hackage as well?

Thanks!

**Comment by gregwebs** [comment]
I just released version 2.0.4

**Comment by Daniel-Diaz** [comment]
Thanks!

**Comment by Daniel-Diaz** [comment]
@gregwebs I can't see it. http://hackage.haskell.org/package/mongoDB

**Comment by gregwebs** [comment]
oops, upload failed. I re-uploaded now.

**Comment by Daniel-Diaz** [comment]
Thanks.
