### ISSUE TITLE
Examples using auth?

### ISSUE THREAD

**Issue by TGOlson** [mongodb-haskell/mongodb#22]
I'm getting pretty confused how to authenticate using this library. Admittedly I'm a little new to some of the Haskell concepts, but could you provide an example of how to connect to a database with authentication?

**Comment by gregwebs** [comment]
You could look at what [persistent-mongoDB is doing](https://github.com/yesodweb/persistent/blob/master/persistent-mongoDB/Database/Persist/MongoDB.hs#L286)

**Comment by VictorDenisov** [comment]
Closing this as old and presumably resolved issue.
