### ISSUE TITLE
Driver doesn't return all documents from the database 

### ISSUE THREAD

**Issue by VictorDenisov** [mongodb-haskell/mongodb#24]
I inserted 7 000 000 documents into a database.testCollection. After that I executed the following program. I received only 97800 docs instead of expected 100 000.

main = do
  config <- readConfig

  CD.withDB (database config) $ do
    cur <- M.find $ (M.select [] "testCollection") {M.limit = 100000}
    drainCursor cur

drainCursor :: M.Cursor -> M.Action IO ()
drainCursor cur = do
    mDoc <- M.next cur
    case mDoc of
      Nothing -> return ()
      Just doc -> do
        liftIO $ putStrLn $ show doc
        drainCursor cur

**Comment by VictorDenisov** [comment]
It looks like the problem exists because mongodb server doesn't return more than one document when
numberToReturn is negative in query or getMore even though the wire protocol documentation states different.

**Comment by VictorDenisov** [comment]
I'm going to email mongodb devs and ask about this behavior. I'll update when I get a response from them.

**Comment by VictorDenisov** [comment]
Addressed by pull request #25. Marking this issue as resolved.

**Comment by jb55** [comment]
I'm pretty sure this introduces a pretty serious regression. On 2.0.5 when I do a simple query against a collection with `rest` I get all `6000` items. On 2.0.6 I always get 101 results.

**Comment by jb55** [comment]
I get this on `master` as well (testing with mongo v2.6.7)

**Comment by jb55** [comment]
I meant to comment on #25 but yeah

**Comment by VictorDenisov** [comment]
Can I see your full program that you are using for testing?

**Comment by VictorDenisov** [comment]
And could you please try selecting your results using this line:

cur <- find $ (select [] "collection") {limit = 6000, batchSize = 6000}

I'm just curious if there is any difference.

**Comment by jb55** [comment]
I'm using the code from the example in the haddocks for testing:

```haskell
main = do
   pipe <- connect (host "127.0.0.1")
   e <- access pipe master "test" run
   print (length e)

run = rest =<< find (select [] "users")
```

Is always 101. I shouldn't have to pass limit or blocksize but I'll try it in a bit.

**Comment by jb55** [comment]
@gregwebs @VictorDenisov `rest =<< (find $ (select [] "collection") {limit = 6000, batchSize = 6000})` works, without an explicit limit or batchsize I get only get `101` results with `rest`

**Comment by VictorDenisov** [comment]
I reproduced this as well. Working on a fix already.

**Comment by VictorDenisov** [comment]
In the mean time you can use this function to get all results. Of course it's better to rewrite it with tail recursion.

```
drainCursor cur = do
  batch <- M.nextBatch cur
  if null batch
    then
      return batch
    else do
      rem <- drainCursor cur
      return $ batch ++ rem
```
