### ISSUE TITLE
gridfs

### ISSUE THREAD

**Issue by paolino** [mongodb-haskell/mongodb#30]
Are there plans to implement the gridfs part of the driver?

**Comment by gregwebs** [comment]
No, you are welcome to give it a try

**Comment by VictorDenisov** [comment]
This issue will be fixed by merging https://github.com/btubbs/haskell-gridfs into this code and referencing authors' names. They approved this approach in this issue: https://github.com/btubbs/haskell-gridfs/issues/1

**Comment by VictorDenisov** [comment]
Added to master.
