### ISSUE TITLE
OverloadedStrings mispelled in comment

### ISSUE THREAD

**Issue by wojtnar** [mongodb-haskell/mongodb#32]
http://hackage.haskell.org/package/mongoDB-2.0.8/docs/Database-MongoDB.html

'OvererloadedStrings' has extra 'er'

**Comment by gregwebs** [comment]
want to send a pull request? You can make the edit without leaving github

**Comment by wojtnar** [comment]
Let me try.

**Comment by wojtnar** [comment]
Whoa! Very cool!
