### ISSUE TITLE
Handle is closed

### ISSUE THREAD

**Issue by glasserc** [mongodb-haskell/mongodb#35]
[This Gist](https://gist.github.com/glasserc/3f45ffbc4b461ea68ca6) reproduces an error that I've hit in a service at work. It seems like what's happening is that the handle goes bad when the query goes wrong. Is there maybe something wrong with the strictness of the query, and it isn't being evaluated correctly? Or does any exception cause the handle to actually close?

It seems like this makes it hard or impossible to recover gracefully from any kind of "latent" error in a query.

**Comment by gregwebs** [comment]
This is only when the query itself contains an exception? If that is the case you could evaluate it before using it. Using something more type-safe such as persistent-mongoDB could help also.

**Comment by glasserc** [comment]
I did work around it by moving the exception-raising code out from the `query` (in my case it was a `read foo :: ObjectId`). But surely if that's what the problem is, then shouldn't `query` be strict in its argument, and `access` be strict in its, so that we don't send half-queries down the wire?

**Comment by gregwebs** [comment]
Not sure if laziness could somehow be useful if inserting large data.

**Comment by VictorDenisov** [comment]
I think it's enough to make psend's argument message strict. Then it will assure that onException catches only real io exceptions not exceptions in users code that produced this message. I'll add it to 2.1.0
