### ISSUE TITLE
SCRAM authentication not working with mongolab

### ISSUE THREAD

**Issue by Yuras** [mongodb-haskell/mongodb#36]
For some reason mongodb on mongolab requires additional message exchange round. The response contains "done":false indicating that the client should send "saslContinue" once more. [Here](https://github.com/Yuras/mongodb/commit/0b4e3d96edaf540f48fdd89dceebb7df86a84a47) is a patch I applied to make it work, though I'm not familiar enough with SCRAM.

@Feeniks AFAIK you implemented SCRAM support. Any comments?

**Comment by Feeniks** [comment]
I cannot replicate. What server version is your mongolab account running? I have asked mongolab support, and they suggest that we should not query build info from the admin database, although this does appear not to be an issue in multi-tenanted environments.

**Comment by Yuras** [comment]
Thank you for reply. Mongodb version is 3.0.7, it is a single node sandbox plan.

[Here](http://haskell-exists.com/mongolab.1.txt) is a dump of a TCP stream of a successful authentication of the standard mongo client (MongoDB shell version: 3.0.7), you can see that client sends one "saslStart" and two "saslContinue" requests. Server responds with "done:false" to all of them except the last one.

I can provide you access to the database e.g. via email.

**Comment by Feeniks** [comment]
From your tcp dump you appear to be running the getLog command against the admin database, which will fail in a multi-tenanted environment.

If you send your login details to ralphmorton@gmail.com, I will have a look.

**Comment by Yuras** [comment]
I just sent you credentials for database access.

> you appear to be running the getLog command against the admin database

Looks like mongo shell does that on startup. The dump doesn't contain any commands I ran manually.

**Comment by Feeniks** [comment]
OK I see the issue. Would you please submit your patch as a pull request?
