### ISSUE TITLE
MongoDB Driver

### ISSUE THREAD

**Issue by christkv** [mongodb-haskell/mongodb#39]
Hi

I've not found any other way to get hold of you.

Thank you for all the work you've been doing on your MongoDB Haskell driver, we're always thrilled to see developers like you in the community.  We have recently decided to formally decommission our Haskell driver, and as a recognition of your work, we'd like to appoint you the official maintainer of the MongoDB Haskell driver. 

We would like to transfer our Haskell driver repo to you. Even though your fork has since surpassed it, this would give you the full commit history and ownership of the driver. If not, we are happy to keep it in the MongoDB repo and point to your driver in the README.

Welcome to the MongoDB Developer community-- perhaps long overdue at this point. :-) We'll invite you to our MongoDB Driver Developer Google group, which is a place for our community-supported driver devs to get the latest info on specs and development from the Drivers Team at MongoDB. 

Please don't hesitate to let me know if you have any questions or concerns. 

Warm regards,

Christian Kvalheim

**Comment by gregwebs** [comment]
Thanks Christian. It is weird that there would have been any perception that MongoDB was doing anything to maintain this driver. The reins were already handed over (years now). Are you trying to delete the `mongoDB/mongoDB-` repo? Or are you stating a preference for this repo to live under `mongoDB`? This repo does have the full commit history: https://github.com/mongodb-haskell/mongodb/commits/master?page=4

**Comment by christkv** [comment]
no we are actually willing to transfer the whole repo to you directly then just fork back with instructions to go to your repo instead.

**Comment by VictorDenisov** [comment]
Christian, is the repository you are talking about on github? Is it possible to compare them before we do any moves?

**Comment by gregwebs** [comment]
@christkv Would it make sense to delete the `mongoDB` repo and then fork this one and put the message there? Otherwise I am not sure how to retain the existing issues here.

**Comment by christkv** [comment]
That is a very good point. But not sure what happens to forks when deleting the parent repository so need to find out by asking github

**Comment by VictorDenisov** [comment]
@christkv I don't even see this driver among community supported drivers. https://docs.mongodb.org/manual/applications/drivers/ Can it be added there?

**Comment by VictorDenisov** [comment]
@christkv Any progress on this? I saw that github allows to detach repositories from their parents. It's a special request and can be done by github administrators. So, we can just detach this repository from its parent and then fork it into mongo repositories.

**Comment by VictorDenisov** [comment]
I'm closing this issue as the conversation seems to have reached a dead end.

**Comment by christkv** [comment]
@VictorDenisov do I need to request that they detach it or is that something you guys need to do ? On our side I think I'll go with just branching, setting it as the default, wiping it and leave a README pointing to this repo. Sorry it took so long to get any feedback it's just been a bit chaotic over the last couple of months and this got forgotten in the commotion.

**Comment by VictorDenisov** [comment]
@christkv I'll post the request to detach the repository. @gregwebs are you ok with detaching the repository? It will make it the top level repository.

**Comment by christkv** [comment]
sounds like the right decision, let me know when you've managed to get it detached and I'll see about getting the haskell repo under mongodb fixed.

**Comment by gregwebs** [comment]
Sounds good

**Comment by VictorDenisov** [comment]
Done. mongodb-haskell/mongodb is a standalone repository now.
