### ISSUE TITLE
allCollections is broken since mongodb-3.0

### ISSUE THREAD

**Issue by hasufell** [mongodb-haskell/mongodb#43]
https://docs.mongodb.org/manual/reference/system-collections/

> \<database\>.system.namespaces
> Deprecated since version 3.0: Access this data using listCollections.
> 
> The \<database\>.system.namespaces collection contains information about all of the database’s collections.

For these versions, `allCollections` always returns an empty list.

**Comment by VictorDenisov** [comment]
Fixed
