### ISSUE TITLE
provide a populate/deepPopulate function

### ISSUE THREAD

**Issue by hasufell** [mongodb-haskell/mongodb#44]
This is a very common functionality to dereference an object into the result query.

I was trying a naive implementation along these lines until I hit #43 :

```hs
-- |Dereference the object reference at the given label location
-- in the given document.
populate :: (MonadIO m, MonadBaseControl IO m)
         => [Label]
         -> Document
         -> Action m Document
populate [] doc     = return doc
populate (l:ls) doc = do
  cs  <- allCollections
  let val' :: ObjectId
      val' = at l doc
  ds <- forM cs $ \c -> (rest =<< find (select ["_id" =: val'] c))
  case headMay $ concat ds of
       Just newdoc -> populate ls (modifyField newdoc l doc)
       Nothing     -> error "Ouch!"


-- |Searches for a field via a label at a given document and
-- replaces the value with another document.
modifyField :: Document  -- ^ replacement value
            -> Label     -- ^ label used for the search
            -> Document  -- ^ document to search
            -> Document
modifyField _ _ [] = []
modifyField i l (d:ds)
  | label d == l = (l := Doc i) : ds
  | otherwise = d : modifyField i l ds
```

Apart from the obvious rough edges, I wonder if there is a more efficient way than iterating over all collections in order to find the match to an `ObjectId`.

`deepPopulate` would then probably use `[[Label]]` or so as first argument instead of `[Label]`.

**Comment by VictorDenisov** [comment]
I'm not sure I understand the request here. Could you please elaborate.

**Comment by hasufell** [comment]
see
http://mongoosejs.com/docs/populate.html
https://www.npmjs.com/package/mongoose-deep-populate

**Comment by VictorDenisov** [comment]
From what I understood so far it looks like it's outside of scope of mongodb driver. Basically you want mongoose for haskell, which is a separate library on top of mongodb driver. What is your opinion @gregwebs ?

**Comment by hasufell** [comment]
> Basically you want mongoose for haskell

Not really. I just want deep population.

**Comment by VictorDenisov** [comment]
Mongoose allows you to define the structure of your documents. And for them this deep population can be implemented more or less efficiently. Generic deep population is inefficient and can easily be implemented on top of mongodb driver. It can be another library that uses mongodb driver. It doesn't need to be a part of the driver.
