### ISSUE TITLE
allCollections always returns an empty list

### ISSUE THREAD

**Issue by Cutuchiqueno** [mongodb-haskell/mongodb#58]
I am new to Haskell and the mongodb driver, so please apologies if I got sth. wrong, but the `allCollections` command always returns an empty list for me. I followed the whole tutorial so there should be a collections `posts`. I can also query this collection and get the data which had been ingested. Nonetheless, it does not appear in the collections list of `allCollections`

**Comment by VictorDenisov** [comment]
I assume you are using mongodb above 3.0. It was reported in #43 . The problem will be fixed in haskell-mongodb 2.1.0. I expect to release it this or next week. Check milestones here for progress.

**Comment by Cutuchiqueno** [comment]
Thx for giving quick answer, I searched the issues before but for some reasons didn't came by issue #43, sorry
