### ISSUE TITLE
inserting is very very slow

### ISSUE THREAD

**Issue by hwa** [mongodb-haskell/mongodb#6]
I tested and find that inserting records is very very slow, about 100 times slower than python client. Have you ever notice that? The simple testing code is here: https://gist.github.com/hwa/e590dac11b789a7aa3f2

**Comment by Herzult** [comment]
Hello,

Is there any news about the performance issues?

I'm currently trying to build some simple read-only web service on top of a MongoDB database but the response times are really bad.

I tried some benchmarking : https://gist.github.com/Herzult/56226dd23d8692d5ac88

**Comment by gregwebs** [comment]
no news. You could check to see if anything improves with 7.10

**Comment by VictorDenisov** [comment]
I noticed that the driver is much faster when we don't reuse the existing connection to the database. Here is an example:

This code is faster:

forM_ docs $ \doc -> do
      pipe <- M.connect (M.host "127.0.0.1")
      vid <- M.access pipe M.master "mongodb-haskell-test" $ M.insert "bigCollection" doc
      putStrLn $ show vid
      M.close pipe

Than this code:

pipe <- M.connect (M.host "127.0.0.1")

forM_ docs $ \doc -> do  
      vid <- M.access pipe M.master "mongodb-haskell-test" $ M.insert "bigCollection" doc
      putStrLn $ show vid
      
M.close pipe

The first code takes only 2 sec to run. The second piece of code takes up to 4 minutes to run.
I'm researching this issue.

**Comment by VictorDenisov** [comment]
Another piece of finding is that unconfirmed writes are much faster(thank you cap) even when we reuse the same connection. So, since unconfirmed writes and confirmed writes one per connection are much faster than many confirmed writes with one connection I can conclude that something is wrong with the queue of replies. Looking further into it...

**Comment by VictorDenisov** [comment]
I'm marking this issue as resolved.
