### ISSUE TITLE
Please provide a proper license tag in the Cabal file

### ISSUE THREAD

**Issue by peti** [mongodb-haskell/mongodb#66]
My understanding is that `Apache-2.0` would be the correct choice.

**Comment by VictorDenisov** [comment]
It's been done already - https://github.com/mongodb-haskell/mongodb/commit/02a47e910874ab37d35e8b8f99f8a2296b9ec060
Do you want a new release any time soon?

**Comment by peti** [comment]
Hi Victor,

 > Do you want a new release any time soon?

Yes, please, that would be great!

**Comment by VictorDenisov** [comment]
Published new version of mongodb and bson packages.
