### ISSUE TITLE
Improve the current Haddock documentation

### ISSUE THREAD

**Issue by psibi** [mongodb-haskell/mongodb#71]
In the `Database.MongoDB` page: https://www.stackage.org/haddock/lts-7.8/mongoDB-2.1.1.1/Database-MongoDB.html

1) Add type signatures for the insertTeam and other similar functions. As a new user, I want to get familiarized with the types as soon as possible.
2) Just add the ghc extensions in the code rather than explicitly stating it. I lost some minutes because of that. :)

**Comment by psibi** [comment]
I can create a PR, if you are interested. :)

**Comment by gregwebs** [comment]
documentation PRs are always welcome!
