### ISSUE TITLE
Mongo 3.6 aggregate now uses cursor for results

### ISSUE THREAD

**Issue by ptillemans** [mongodb-haskell/mongodb#86]
From 3.6 on mongo makes the cursor attribute mandatory ( unless explain  is passes ) and returns the data as a cursor.

This breaks the current implementation

**Comment by VictorDenisov** [comment]
Cool. Thanks for filing.

**Comment by VictorDenisov** [comment]
@ptillemans Please take a look at PR https://github.com/mongodb-haskell/mongodb/pull/87 whether it makes sense to you.
