### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by JonathanLorimer** [mongodb-haskell/mongodb#99]
Hey, I read through the documentation and couldn't find a way to provide a username and password when connecting. Is Mongo Auth supported by this library?

**Comment by VictorDenisov** [comment]
Hi @JonathanLorimer, authentication is here: http://hackage.haskell.org/package/mongoDB-2.5.0.0/docs/Database-MongoDB-Query.html#g:3

**Comment by JonathanLorimer** [comment]
@VictorDenisov Thank you!
